---
title: "Worksheet#2"
author: "John Lyxton L. Camarista"
date: "2024-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### 1. Create a vector using : operator
    
```{r}
  # - a. Sequence from -5 to 5. Write the R code and its output. 
  # Describe the output.
seq_neg5_to_5 <- -5 : 5
seq_neg5_to_5
```
  
```{r}
  # - b. x <- 1:7. What will be the value of x?
x <- 1 : 7
x


```
#### 2. Create a vector seq() function
```{r}
# - a. seq(1, 3, by=0.2) specify step size
#         Write the R script and its output. Describe the output.
seq(1, 3, by=0.2)

```
#### 3. A factory has a census of its workers. There are 50 workers in total. The following list shows their ages: 34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50,  37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18.

```{r}
workers <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50,  37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)
# - a. Access 3rd element, what is the value?
print(paste(workers[[3]], "is the value of the 3rd element"))

```
```{r}
# - b. Access the 2nd and 4th element, what is the value?
print(paste(workers[[2]],"and", workers[[4]], "is the value of the 2nd and 4th element respectively"))
```
```{r}
#- c. Access all but the 4th and the 12th element is not included. Write the R script and its output.
excluded <- workers[-c(4, 12)]
excluded
```
#### 4. Create a vector x <- c("first" = 3, "second" = 0, "third" = 9 ). Then named the vector, names(x)
```{r}
# - a. Print the results. Then access x[c("first", "third")].
# describe the output.
x <- c("first" = 3, "second" = 0, "third" = 9)
x

```
```{r}
# - b. Write the code and its output.
print(x[c("first", "third")])
```


#### 5. Create a sequence x from -3:2.
```{r}
x <- c(-3:2)
```
```{r}
#- a. Modify 2nd element and change it to 0.
# Describe the output
#- b. Write the code and its output.
x[2] <- 0
x

```
```{r}
#- b. Write the code and its output.
print("the output of the second element becomes 0.")
```

#### 6. The Following data shows the diesel fuel purchased by Mr. Cruz

```{r}
#- create a data frame for the month, price per liter (php) and purchase-quantity (liter). Write the R scripts and its output.
months <- c("Jan", "Feb", "March", "April", "May", "June")
price_per_liter <- c(52.50, 57.25, 62.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25L, 30L, 40L, 50L, 10L, 45L)

diesel_data <- data.frame(Month = months, Price_per_liter_PhP = price_per_liter, Purchase_quantity_Liters = purchase_quantity)

print(diesel_data)

```
```{r}
#- What is the average fuel expenditure of Mr. Cruz from Jan to June? Note: Use weighted.mean(liter, purchase). Write the R scripts and its output.
ave_fuel_expenditure <- weighted.mean(diesel_data$Price_per_liter_PhP, diesel_data$Purchase_quantity_Liters)
print(paste(ave_fuel_expenditure, "is the average fuel expenditure of Mr. Cruz from January to June"))
```


